apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  # Storage class will be set via Kustomize overlay
  resources:
    requests:
      storage: 20Gi
